### PR TITLE
Jstanleyx patch 1

### PR DESCRIPTION
**Pull request by jstanleyx**
fixed missing lines

### CODE REVIEW

**Comment by allisonpenko** [comment]
@jstanleyx Please see previous comment about changes and open pull request to merge into development 1st. Thanks!

**Comment by jstanleyx** [comment]
I don't know what edits you made to the code in this patch. It is a
stand-alone version that works here. What does not work? I need to know.

The purpose for the last two weeks I've spent working on this is to
replace the ad-hoc recreation of the wheel and divergence from Argus
that was created when Rob recreated wheels for the UAV demo. And all of
this is at his request. It was specifically to convert to using the
PIXel toolbox, but as a side effect it included the distort/undistort
functions. 

Step 1 is to add the functions that integrate the UAV demo code with
Argus, with a couple of changes to some core UAV functions so they work
either way, and write a demo program that uses them so other people can
test the new code. That's sampleAerielleVideoDemoPIX.m. I could have
simply changed sampleAerielleVideoDemo, but that makes it hard to
compare the results of the two ways of doing things.

Step 2 is removing the obsolete functions like DJIDistort, etc after
code is in place to do the new way. That includes removing
sampleAerielleVideoDemo.m. It will be obsolete, too.

What would be an incredible waste of everyone's time is if your
development branch makes extensive use of DJIUndistort, e.g., and when
you merge your branch back we wind up with more uses of an obsolete
function and it becomes even harder to get rid of it, where if we can
get rid of this function from master before your merge then it becomes
obvious when you test master that the function is gone. Or if you have
lots of new functions that make heavy use of the 'insts' or 'stack'
structs and they all change because they go away in the new version. 

Removing the demo script for how to do it the new way makes all the
other work useless because nobody will know how to do it the new way, or
be able to test it easily.

**Comment by KateBrodie** [comment]
I haven't been intimately involved in the details of this thread, but I think the main point is that nothing should be merged into Master without first being merged into the Development Branch.  So the "obsolete" function needs to be properly removed and tested in the development branch, before that branch can be merged into Master. Master should always be the most tested, operational version of the code - which sometimes means it may not be the most "correct" or "efficient" version.  The updates MUST first be tested in development before they can be merged in Master. At least, that's how I understand the rules we've set up and are trying to follow.  You never want to "break" the master branch.

**Comment by allisonpenko** [comment]
Hi John, 

I didn't mean that we shouldn't use what you've worked on the last 2 weeks. We just want to make sure that the code runs without errors and is well documented before merging to the Master branch. I'm a good person to test because I have no previous Argus code/DB on my computer, so I reflect a new user to the code. I only change a couple lines (mainly added filesep to path variables). You can see the differences between my and your code by clicking on your branch and clicking "compare" on the right hand side. Then select my branch (allison-demo-test) to compare to. 

I tested the sampleAerielleVideoDemoPIX.m and it works if you clone the PIXel-Toolbox and add the path. 

Please merge your branch (jstanleyx-patch-1) into the development branch. As soon as the documentation for the sampleAerielleVideoDemoPIX.m and the PIXel-Toolbox is complete, we can merge it into the master branch.

**Comment by jstanleyx** [comment]
On Fri, 2017-03-24 at 14:03 -0700, Allison Penko wrote:

> I tested the sampleAerielleVideoDemoPIX.m and it works if you clone
> the PIXel-Toolbox and add the path.

Yes, you need the PIXel toolbox.

> Please merge your branch (jstanleyx-patch-1) into the development
> branch. As soon as the documentation for the
> sampleAerielleVideoDemoPIX.m and the PIXel-Toolbox is complete, we can
> merge it into the master branch.

Ok. Pull request generated. 

What more documentation for sampleAerielle... and PIXel-Toolbox is
necessary?

**Comment by allisonpenko** [comment]
> What more documentation for sampleAerielle... and PIXel-Toolbox is necessary?

The wiki describing the Demo in the UAV-Processing-Toolbox needs to tell the user which Demo script to run (right now it says to run sampleAerielleVideoDemo.m) and which Toolboxes they need to run the demo (and that they need to add the path to the PIXel toolbox).   Ideally, all the code to run a particular Demo should be in one repository. But since this now requires a separate toolbox, we need documentation to make sure the user knows what to download and that they need to either add the path to their permanent path list in Matlab, or include a line in the demo script that would add it when they run it. Right now, if the user was to run sampleAerielleVideoDemoPIX.m, they'd have no idea that they needed external functions and the script would error immediately with an unknown function (as it did for me until I downloaded the toolbox and pointed matlab to it).

As soon as the wiki is updated, I think it's fine to merge into the master branch.

Additionally, the PIXel Toolbox Manual really should get transcribed to the Wiki in it's repository to be consistent with all the other toolbox repositories we have within the CIRN GitHub.

**Pull request closed without merging**
