### PR TITLE
change to use pixel toolbox

### PR DESCRIPTION
**Pull request by jstanleyx**
change to using 1. pixel toolbox for pix lists, 2. eliminate DJI specifics from distort/undistort. Something else, but I don't remember the question.

### CODE REVIEW

**Comment by mpalmsten** [comment]
This needs more discussion, holding for now.

**Comment by RobHolman** [comment]
Just to be clear, doesn't closing an issue mean it is resolved? @mpalmsten

**Comment by mpalmsten** [comment]
@RobHolman, this development would have removed backwards compatibility with your original version of the UAV toolbox, we added in the PIXelToolbox without removing the compatibility (@allisonpenko, please confirm that this is correct). Do we want it to be backwards compatible?

**Comment by jstanleyx** [comment]
Rob's original UAV toolbox broke backwards compatibility with existing CIL methods of dealing with pixels and instruments. It forces users to manage a lot of bookkeeping that we've already written code to deal with. This is an ideal way of having multiple users all trying to reinvent the pixel toolbox wheel on their own, with multiple paths to nirvana and each one a home for bugs and issues. 

For example, how do you deal with the fact that real world coordinates are not regularly spaced when working in pixel space, and that asking for a specific x,y,z is not going to return data at that x,y,z? Or that once you create two instruments, you may very well be wasting time collecting the same pixel more than once? One user writes his own pixel toolbox to deal with the former issue; the second writes his to deal with the latter. They are incompatible, so neither one can trivially implement the other's solution. 

And we should be looking to forward compatibility. I.e., if they move into a fuller Argus/CIL user experience, all of a sudden there is a different way of dealing with things that their personally written toolbox is incompatible with.

But the issue is closed.

**Pull request closed without merging**
