### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jstanleyx**
sampleAerielleVideoDemoPIX -- uses pixel toolbox to make pixel insts. Various tweaks and some new functions to deal with this.

### CODE REVIEW

**Comment by mpalmsten** [comment]
I found an error in the upload/commit that was made on Feb 2 to add the copyright info. Line 34 from makeUAVPn.m, which opened a gui so the user can define a local directory to store the demo data with the variable name inputs.pnIn, was somehow deleted. I think that John then edited the latest version of demoInputFile.m so to fix that deletion, but that fix is not platform independent. So, line makeUAVPn.m should be edited to include this line:

in.pnIn = uigetdir([],'select local demo storage directory');       % local demo storage location

and lines 12-14 should be deleted from demoInputFile.m

**Comment by mpalmsten** [comment]
Line 50 of findUVnDOF.m calls distort.m. I think it should call distortCalTech.m? 

For me calling distort.m causes an error because my distort.m is the traditional Argus one. I'm assuming for people without the Argus toolbox, this will cause a error.

**Comment by jstanleyx** [comment]
I see the problem. I uploaded all the files to master and it forced the 
creation of patch 1. But it didn't upload all of them, it skipped the ones 
in neededCILRoutines. So I uploaded THOSE to master, and it created patch 
2. Sigh.

I've now put them all in patch 1, so download that and distort will be 
fixed. I've also closed the pull request for patch 2, and I'm about to 
delete the patch itself if I can figure out how to.

This is now also the version of distort and undistort in the Argus CIL 
code, and distortCaltech has been added to that. Also un.

On Wed, 22 Mar 2017, mpalmsten wrote:

> Line 50 of findUVnDOF.m calls distort.m. I think it should call distortCalTech.m?
>
> For me calling distort.m causes an error because my distort.m is the traditional Argus one. I'm assuming for people without the Argus toolbox, this will cause a error.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Coastal-Imaging-Research-Network/UAV-Processing-Toolbox/pull/10#issuecomment-288619625

--
stanley@oce.orst.edu

**Comment by mpalmsten** [comment]
[Here's](https://kb.swarthmore.edu:8443/display/ITSDOCS/Roll+back+git+remote+to+a+previous+commit)
 instructions on how to roll back a commit if you didn't figure it out.

**Comment by allisonpenko** [comment]
John - Meg and I updated the master - fixing the bugs that were created by accidental line deletion when inserting the copyright information. You first need to update your local copy with those new changes by typing in the command line:
>> git checkout jstanleyx-patch-1  #will switch to your branch 
>> git pull origin master       #will update your jstanelyx-patch-1 branch with the changes in the master

There are a lot of things in this merge that causes things to break that need to be addressed. I think the best way forward is to discuss them all next week and make sure the code is fully working before merging into the master.

**Comment by jstanleyx** [comment]
Every file that ended with an incomplete line (no newline at the end of
the last line) lost that line.

General rule: always make sure you end the last line of your scripts.

**Comment by jstanleyx** [comment]
I've just fixed a couple of places that needed to test 'insts' for pixel
and failed, and a couple of fileseps in sampleUAVDemo where necessary,
and put them into jstanleyx-patch-1.

I've run this code in both modes -- sampleUAVDemo and sampleUAVDemoPIX
and it runs without failure. For the PIX version, you need the
PIXel-Toolbox.

**Pull request closed without merging**
