### PR TITLE
added ability to use known camera info (with uncertainty)

### PR DESCRIPTION
**Pull request by nosliwg**
known camera info can be used as an extra constraint, e.g. for cases with few GCPs

### CODE REVIEW

**Comment by hokiespurs** [comment]
@nosliwg, looks useful! Can this optimization algorithm also output a covariance matrix for the computed Beta parameters?.. I'm looking into doing some uncertainty propagation.

**Comment by nosliwg** [comment]
Unfortunately not, Richie.  I used matlab 'globalsearch' for optimization, which doesn't compute error covariance.  The inverse hessian of 'costFN' (evaluated at 'beta') is what you need I think, would be a good extension, but I don't see a canned routine for computing that.

**Comment by hokiespurs** [comment]
Thanks for checking, @nosliwg.  I'm not too familiar with the inverse hessian, but will look into it.  Alternatively maybe future code could leverage your implementation of the globalsearch to initialize Beta for a weighted nonlinear or total least squares approach, where an initial guess at the camera location is input as an extra observation equation with uncertainty.  Do you think that would yield the same results, or is the globalsearch optimization doing more than rejecting local minima?.. I don't know much about this form of regression.

**Comment by nosliwg** [comment]
@hokiespurs, I hadn't heard of total least squares before, but looks like that's what the code is already doing: the camera position (with uncertainty) is incorporated via an extra penalty function in the lsq fit.  Why do statisticians always have five names for every concept!  As for globalsearch, that's just b/c I was having problems with local minima.

**Comment by hokiespurs** [comment]
@nosliwg, haha the different nomenclature drives me nuts!  Now that I'm thinking about it, I may have misspoke on total least squares.  The "cost function" for total least squares is on the residuals of the input variables(pixel coords, gcps coords), not the unknowns... so it may be a bit different. I'll have to think about it some more.  Regardless, I haven't found total least squares built into matlab, and coding it manually for the camera pose estimation takes a few hundred lines of code with all the partial derivatives and explicitly running the iterative least squares... so your method is MUCH cleaner.  And I really like the global search implementation to avoid local minima, I think that will prove very useful.  👍

**Comment by nosliwg** [comment]
I was afraid of that.  I believe @hokiespurs has been working on a new tool that can do the same job without the toolbox (and also is a potential open-source nlinfit replacement!).  This would be a good use case.

**Comment by hokiespurs** [comment]
@mpalmsten, I tested this when @nosliwg first made the pull request and the example worked for me.  I don't remember doing very rigorous testing, though, so I'd recommend another user test it before merging

Alternatively, I've been working with @nosliwg to replace nlinfit with a least squares method that 
a) implements the camera position uncertainty as observation equations
b) replaces nlinfit and doesn't rely on a toolbox

If there's no urgency to merge this pull request, this new function should be ready in a month or so.

**Comment by mpalmsten** [comment]
Hey @hokiespurs ! We are getting ready for the next bootcamp in June and want to merge in @nosliwg's geom fix. Did you ever get your new function ready that removes the Matlab Toolbox dependencies?

**Comment by hokiespurs** [comment]
Hey @mpalmsten! Yes, I did finish that function.  I have it on a different respository with a bunch of other general purpose matlab functions.

[Function](https://github.com/hokiespurs/general-purpose-matlab/blob/master/leastSquares/lsr/lsr.m)
[Example Usage](https://github.com/hokiespurs/general-purpose-matlab/blob/master/leastSquares/lsr/exampleLsr.m)
[Documentation](https://github.com/hokiespurs/general-purpose-matlab/blob/master/leastSquares/lsr/doc/doclsr.pdf)

I don't know the right protocol for copying or linking between different repositories, but feel free to just copy the lsr function (and any others you find useful) into this repository.

**Comment by eswanson-usgs** [comment]
Branch is 50+ commits behind, so decision was made with CIRN leadership to close the pull request and delete the branch

**Pull request closed without merging**
