### PR TITLE
added use of uncertain camera geom as a constraint

### PR DESCRIPTION
**Pull request by nosliwg**
If an a-priori estimate of geometry is available, use it plus uncertainty as an additional constraint on solution.  Could be useful in cases with not enough GCPs

### CODE REVIEW

**Comment by allisonpenko** [comment]
Hey @nosliwg ! Thanks for this enhancement! A couple of things - 
1) I wanted to make sure you just wanted the changes in the Demo and not in the actual code repository. I'm not familiar with this part of the code, so @mpalmsten, @KateBrodie, @SRHarrison  would likely be better to review.
2) If so, please add some documentation to the wiki about the changes to the Demo
3) Also please do a pull request into the development branch, not the master (change the base branch in the upper left hand side on the pull request page). You'll have to close this one and create a new request. 

Thanks!

**Comment by mpalmsten** [comment]
@nosliwg can you push this to the development branch?

**Comment by allisonpenko** [comment]
Closing - please push to development branch

**Comment by nosliwg** [comment]
sorry for delay.  Pushing to dev.  Suggest leaving in demo version for now, and I will add documentation as requested

**Pull request closed without merging**
