### PR TITLE
added lens calibration demo to repo

### PR DESCRIPTION
**Pull request by allisonpenko**
Includes all the images and code (including the "answers" in the Calib_ResultsDemoOutput folder) for a lens calibration demo. All steps included in lensCalibDemo.m

### CODE REVIEW

**Comment by JennaBrown-USGS** [comment]
@allisonpenko  I get an error running "lesCalibDemo.m" because you haven't defined "YOUR_DIRECTORY" and "YOUR_MATLAB_DIRECTORY".

**Comment by allisonpenko** [comment]
@JennaBrown-USGS So if you change "YOUR_DIRECTORY" and "YOUR_MATLAB_DIRECTORY" to your working directory and your matlab directory, respectively, do you get any other errors? :)

I can change it to uigetdir so the user can define it that way if it isn't clear.

**Comment by allisonpenko** [comment]
@JennaBrown-USGS can you pull the new code and try now? I added uigetdir commands

**Comment by JennaBrown-USGS** [comment]
Yep, it works in Matlab R2016b on Windows.

I think it makes more sense for the user to select the directory, rather than get an error if they just 'Run' the lensCalibDemo.

**Comment by allisonpenko** [comment]
Thanks @JennaBrown-USGS. if the updated code with the uigetdir commands works for you, can you please approve the request?

**Pull request merged**
